server:
  port: 8080
spring:
  application:
    name: alibaba-consumer
dubbo:
  registry:
    address: nacos://localhost:8848
  application:
    name: alibaba-consumer
    qos-enable: false
    qos-accept-foreign-ip: false
  #启动不检查提供者
  consumer:
    check: false