server:
  port: 8080
spring:
  application:
    name: alibaba-consumer
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  application:
    name: alibaba-consumer
    qos-enable: false
    qos-accept-foreign-ip: false